derlecalistir: Program calistir

Program:Node AVL Stack Person Test
	g++ ./lib/Node.o ./lib/AVL.o ./lib/Stack.o ./lib/Person.o ./lib/Test.o -o ./bin/program
Node:
	g++ -I "./include" -c ./src/Node.cpp -o ./lib/Node.o
AVL:
	g++ -I "./include" -c ./src/AVL.cpp -o ./lib/AVL.o
Stack:
	g++ -I "./include" -c ./src/Stack.cpp -o ./lib/Stack.o
Person:
	g++ -I "./include" -c ./src/Person.cpp -o ./lib/Person.o
Test:
	g++ -I "./include" -c ./src/Test.cpp -o ./lib/Test.o
calistir:
	./bin/program.exe